{
  imports = [
    ./ai-server/nixos.nix
    ./audio/nixos.nix
    ./chromium/nixos.nix
    ./autologin/nixos.nix
    ./backlight/nixos.nix
    ./bluetooth/nixos.nix
    ./colemak/nixos.nix
    ./disk-encryption/nixos.nix
    ./docker/nixos.nix
    ./emulation-client/nixos.nix
    ./emulation-server/nixos.nix
    ./file-sharing/nixos.nix
    ./fingerprint/nixos.nix
    ./firewall/nixos.nix
    ./game-streaming/nixos.nix
    ./git-server/nixos.nix
    ./graphics/nixos.nix
    ./headscale/nixos.nix
    ./input-remapper/nixos.nix
    ./home-network/nixos.nix
    ./kde/nixos.nix
    ./kanata/nixos.nix
    ./logitech/nixos.nix
    ./power-management/nixos.nix
    ./printers/nixos.nix
    ./network-manager/nixos.nix
    ./nextcloud/nixos.nix
    ./onlyoffice/nixos.nix
    ./openssh/nixos.nix
    ./restic-backup/nixos.nix
    ./restic-target/nixos.nix
    ./reverse-proxy/nixos.nix
    ./secure-boot/nixos.nix
    ./sops/nixos.nix
    ./file-manager/nixos.nix
    ./tailnet/nixos.nix
    ./tailscale-client/nixos.nix
    ./touchpad/nixos.nix
    ./amd-overdrive/nixos.nix
    ./vaultwarden/nixos.nix
    ./wake-proxy/nixos.nix
    ./webcam/nixos.nix
    ./waydroid/nixos.nix
    ./wayland-security/nixos.nix
    ./xserver/nixos.nix
  ];
}
