{
  imports = [
    ./audio
    ./autologin
    ./backlight
    ./bluetooth
    ./colemak
    ./disk-encryption
    ./docker
    ./emulation-server/system.nix
    ./file-sharing
    ./fingerprint
    ./firewall
    ./game-streaming/system.nix
    ./git-server
    ./graphics
    ./headscale
    ./kde
    ./keyboard
    ./logitech
    ./power-management
    ./printers
    ./networking
    ./openssh
    ./reverse-proxy
    ./secure-boot
    ./sops/system.nix
    ./file-manager/system.nix
    ./tailnet
    ./tailscale-client
    ./touchpad
    ./undervolting
    ./webcam
    ./waydroid
    ./wayland-security
    ./xserver
  ];
}
