{ ... }: {
  imports = [
    ./autorandr
    ./battery-monitor
    ./chromium
    ./communication
    ./controller
    ./controls
    ./development
    ./direnv
    ./emulation-client
    ./emulation-server/user.nix
    ./firefox
    ./flatpak
    ./game-streaming/user.nix
    ./games
    ./general
    ./git
    ./kanshi
    ./launcher
    ./localsend
    ./notifications
    ./picom
    ./polybar
    ./qutebrowser
    ./secrets
    ./shell
    ./starship
    ./terminal
    ./theming
    ./file-manager/user.nix
    ./waybar
    ./window-manager
    ./x11
    ./zellij
  ];
}
