return {
  require('settings'),
  require('nvim-tree-config'),
  require('bufferline-config'),
  require('indent-blankline-config'),
  require('instant-config'),
  require('autopairs-config'),
  require('feline-config'),
  require('lsp-config'),
  require('cmp-config'),
  require('lightbulb-config'),
  require('keymappings'),
  require('telescope-config'),
  require('treesitter-config'),
  require('fidget-config'),
}
