{
  imports = [
    ./audio
    ./autologin
    ./backlight
    ./bluetooth
    ./colemak
    ./disk-encryption
    ./docker
    ./fingerprint
    ./firewall
    ./game-streaming
    ./graphics
    ./kde
    ./keyboard
    ./logitech
    ./power-management
    ./printers
    ./networking
    ./secure-boot
    ./thunar
    ./touchpad
    ./undervolting
    ./waydroid
    ./wayland-security
    ./xserver
  ];
}
