{ config, lib, pkgs, ... }:

with lib;

{
  options.controller = {
    enable = mkEnableOption "Enable controller support and custom mappings";

    type = mkOption {
      type = types.enum [ "ps5" "xbox" "generic" ];
      default = "ps5";
      description = "Type of controller to configure";
    };

    mangohudToggle = {
      enable = mkOption {
        type = types.bool;
        default = true;
        description = "Enable MangoHud toggle via controller buttons";
      };

      buttons = mkOption {
        type = types.listOf (types.enum [ "square" "triangle" "circle" "x" "share" "options" "l3" "r3" ]);
        default = [ "square" "triangle" ];
        description = "Controller buttons that trigger MangoHud toggle";
      };

      autoStart = mkOption {
        type = types.bool;
        default = true;
        description = "Automatically start controller monitoring service";
      };
    };

    customMappings = {
      enable = mkOption {
        type = types.bool;
        default = false;
        description = "Enable custom controller button mappings";
      };

      mappings = mkOption {
        type = types.attrsOf types.str;
        default = {};
        example = {
          "l3+r3" = "screenshot";
          "share+options" = "record";
        };
        description = "Custom button combination to command mappings";
      };
    };

    rumble = {
      enable = mkOption {
        type = types.bool;
        default = true;
        description = "Enable controller rumble/haptic feedback";
      };
    };

    ledSettings = {
      enable = mkOption {
        type = types.bool;
        default = false;
        description = "Enable custom LED settings for supported controllers";
      };

      color = mkOption {
        type = types.str;
        default = "blue";
        description = "LED color for supported controllers";
      };

      brightness = mkOption {
        type = types.int;
        default = 128;
        description = "LED brightness (0-255)";
      };
    };
  };

  config = mkIf config.controller.enable {
    home.packages = with pkgs; [
      evtest
      coreutils
      inotify-tools
      wtype
      procps
    ] ++ optionals config.controller.customMappings.enable [
      # Add additional packages for custom mappings if needed
    ];

    # MangoHud toggle script
    home.file."bin/controller-mangohud-toggle.sh" = mkIf config.controller.mangohudToggle.enable {
      text = let
        controllerType = config.controller.type;
        buttons = config.controller.mangohudToggle.buttons;
        
        buttonMappings = {
          ps5 = {
            square = "BTN_WEST";
            triangle = "BTN_NORTH"; 
            circle = "BTN_EAST";
            x = "BTN_SOUTH";
            share = "BTN_SELECT";
            options = "BTN_START";
            l3 = "BTN_THUMBL";
            r3 = "BTN_THUMBR";
          };
          xbox = {
            x = "BTN_WEST";
            y = "BTN_NORTH";
            b = "BTN_EAST"; 
            a = "BTN_SOUTH";
            back = "BTN_SELECT";
            start = "BTN_START";
            l3 = "BTN_THUMBL";
            r3 = "BTN_THUMBR";
          };
          generic = {
            btn1 = "BTN_SOUTH";
            btn2 = "BTN_EAST";
            btn3 = "BTN_WEST";
            btn4 = "BTN_NORTH";
            select = "BTN_SELECT";
            start = "BTN_START";
            l3 = "BTN_THUMBL";
            r3 = "BTN_THUMBR";
          };
        };

        controllerNames = {
          ps5 = "DualSense Wireless Controller";
          xbox = "Xbox.*Controller";
          generic = ".*[Cc]ontroller.*";
        };

        generateButtonChecks = buttons: let
          currentMappings = buttonMappings.${controllerType};
          buttonChecks = map (btn: 
            ''if echo "$line" | grep -q "${currentMappings.${btn}}.*value 1"; then
        echo "${btn} button pressed - toggling MangoHud..."
        toggle_mangohud
        echo "MangoHud toggled with ${btn}!"
        sleep 0.5  # Prevent rapid toggling
    fi''
          ) buttons;
        in concatStringsSep "\n        " buttonChecks;

      in ''
        #!${pkgs.bash}/bin/bash
        # Controller to MangoHud toggle script (Gamescope compatible)
        # Generated by NixOS controller module
        
        set -euo pipefail
        
        # Logging function
        log() {
            echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" >&2
        }
        
        # MangoHud toggle function for gamescope
        toggle_mangohud() {
            # Method 1: Try to find and signal the gamescope process
            if pgrep -f "gamescope" >/dev/null; then
                log "Found gamescope process, sending F12 to toggle MangoHud"
                # Use gamescope's built-in MangoHud toggle (F12 by default)
                if command -v wtype >/dev/null 2>&1; then
                    wtype -k F12
                elif [ -e /dev/input/by-path/*kbd* ]; then
                    # Fallback: write directly to keyboard device
                    echo -ne '\e[24~' > /dev/tty 2>/dev/null || true
                fi
            else
                log "No gamescope process found, trying alternative methods"
                # Method 2: Toggle via MangoHud control file if it exists
                if [ -w "/tmp/mangohud_toggle" ]; then
                    echo "toggle" > /tmp/mangohud_toggle
                elif [ -w "/run/user/$(id -u)/mangohud_toggle" ]; then
                    echo "toggle" > "/run/user/$(id -u)/mangohud_toggle"
                else
                    log "WARNING: Could not toggle MangoHud - no gamescope or control file found"
                fi
            fi
        }
        
        # Find controller device
        find_controller() {
            local controller_name="${controllerNames.${controllerType}}"
            log "Looking for controller: $controller_name"
            
            local controller_event
            controller_event=$(cat /proc/bus/input/devices 2>/dev/null | \
                grep -B 5 -A 5 "$controller_name" | \
                grep "Handlers" | \
                grep -o "event[0-9]*" | \
                head -1)
            
            if [ -n "$controller_event" ]; then
                echo "/dev/input/$controller_event"
                return 0
            fi
            return 1
        }
        
        # Monitor single controller
        monitor_controller() {
            local controller_path="$1"
            
            if [ ! -r "$controller_path" ]; then
                log "ERROR: No read permission for $controller_path"
                log "Current user: $(whoami), Groups: $(groups)"
                log "Device permissions: $(ls -la "$controller_path" 2>/dev/null || echo "Device not found")"
                return 1
            fi
            
            log "Successfully found ${controllerType} controller at $controller_path"
            log "Enabled buttons: ${concatStringsSep ", " buttons}"
            log "Starting event monitoring..."
            
            # Monitor controller events
            evtest "$controller_path" 2>/dev/null | while IFS= read -r line; do
                ${generateButtonChecks buttons}
            done
        }
        
        # Main loop with hotplug support
        main() {
            log "Controller MangoHud Toggle Service started"
            log "Monitoring for ${controllerType} controllers..."
            log "Supported buttons: ${concatStringsSep ", " buttons}"
            
            while true; do
                local controller_path
                if controller_path=$(find_controller); then
                    log "Controller connected: $controller_path"
                    monitor_controller "$controller_path" || {
                        log "Controller monitoring failed, will retry..."
                    }
                else
                    log "No controller found, waiting for connection..."
                fi
                
                # Wait before retrying
                sleep 2
                
                # Check for new devices using inotify if available
                if command -v inotifywait >/dev/null 2>&1; then
                    log "Waiting for new input devices..."
                    timeout 30 inotifywait -e create /dev/input/ 2>/dev/null || true
                fi
            done
        }
        
        # Handle signals gracefully
        trap 'log "Service stopping..."; exit 0' TERM INT
        
        main
      '';
      executable = true;
    };

    # SystemD service for MangoHud toggle
    systemd.user.services.controller-mangohud-toggle = mkIf (config.controller.mangohudToggle.enable && config.controller.mangohudToggle.autoStart) {
      Unit = {
        Description = "Controller MangoHud Toggle Service";
        After = [ "multi-user.target" ];
      };

      Service = {
        Type = "simple";
        ExecStart = "%h/bin/controller-mangohud-toggle.sh";
        Restart = "always";
        RestartSec = "5s";
        Environment = [
          "XDG_RUNTIME_DIR=/run/user/%i"
        ];
      };

      Install = { WantedBy = [ "default.target" ]; };
    };

    # Custom controller mappings script (future expansion)
    home.file."bin/controller-custom-mappings.sh" = mkIf config.controller.customMappings.enable {
      text = ''
        #!${pkgs.bash}/bin/bash
        # Custom controller mappings
        # This can be expanded for additional custom commands
        echo "Custom controller mappings not yet implemented"
      '';
      executable = true;
    };

    # Controller configuration hints
    home.file."docs/controller-usage.md" = {
      text = ''
        # Controller Configuration

        ## Current Setup
        - Controller Type: ${config.controller.type}
        - MangoHud Toggle: ${if config.controller.mangohudToggle.enable then "Enabled" else "Disabled"}
        ${optionalString config.controller.mangohudToggle.enable "- Toggle Buttons: ${concatStringsSep ", " config.controller.mangohudToggle.buttons}"}
        - Auto-start Service: ${if config.controller.mangohudToggle.autoStart then "Enabled" else "Disabled"}

        ## Usage
        ${optionalString config.controller.mangohudToggle.enable ''
        ### MangoHud Toggle
        Press any of the configured buttons (${concatStringsSep ", " config.controller.mangohudToggle.buttons}) to toggle MangoHud on/off while gaming.
        ''}

        ## Manual Control
        - Start monitoring: `systemctl --user start controller-mangohud-toggle`
        - Stop monitoring: `systemctl --user stop controller-mangohud-toggle`
        - Check status: `systemctl --user status controller-mangohud-toggle`
        - Run manually: `~/bin/controller-mangohud-toggle.sh`

        ## Troubleshooting
        - Check connected controllers: `cat /proc/bus/input/devices | grep -i controller`
        - Test controller input: `evtest /dev/input/eventXX`
        - View service logs: `journalctl --user -u controller-mangohud-toggle -f`
      '';
    };
  };
}